title: <center>Laboratório de Genômica Evolutiva</center>
logo: /assets/img/logo.png
description: </center>Site do Laboratório da professora Dra. Mariana Nery</center>
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
